FROM zebradil/moodle:3.2

RUN cd /var/www/localhost/htdocs \
 && git clone git://github.com/trampgeek/moodle-qtype_coderunner.git question/type/coderunner \
 && git clone git://github.com/trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner.git question/behaviour/adaptive_adapted_for_coderunner

